name: Comment PR opened

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Get event details
      env:
        EVENT_CONTEXT: ${{ toJSON(github.event) }}
    - name: Update credentials
      env: 
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run script
      run: python run_pr_analysis.py