name: Comment PR opened

on:
  pull_request:
    types: [opened, edited, closed, reopened, synchronize, converted_to_draft, ready_for_review, review_requested]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - uses: action.yaml
      with:
        database-id: 8ad76183848046f2bb81658f92b3a431
