name: Comment PR updates

on:
  pull_request:
    types: [opened, edited, closed, reopened, synchronize, converted_to_draft, ready_for_review, review_requested]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: kolesnikov-pasha/github-pr-linker@v1.0.1
      with:
        database-id: 8ad76183848046f2bb81658f92b3a431
        notion-token: ${{ secrets.NOTION_TOKEN }}
