name: Comment PR opened

on:
  pull_request: 
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Get event details
      env:
        EVENT_CONTEXT: ${{ toJSON(github.event) }}
      run: echo $EVENT_CONTEXT
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Grant execute permission for script
      run: chmod +x extract_pr_info_and_comment_open.sh
    - name: Run script
      run: ./extract_pr_info_and_comment_open.sh